Repository ElectroLodge/Hacktober_Fest_2023, pull requests merged in 2022-10, with the labels that each got.

#4 Added the rock paper scissor game
  rock-paper-scissor-game.py
Labels: good first issue

#6 Find whether the number is a even or odd
  even-or-odd.py
Labels: hacktoberfest-accepted

#8 String execute issue number #9
  executeastring.py
Labels: hacktoberfest-accepted

#12 added a web crawler
  webcrawler.py
Labels: hacktoberfest-accepted

#13 Simple Calculator
  roamnnumbersintodecimal.py
  simplecalculator.py
Labels: hacktoberfest-accepted

#16 simple area finder
  area.py
Labels: hacktoberfest-accepted

#19 added a password generator
  passwordgenerator.py
Labels: hacktoberfest-accepted

#20 done
  sumofodd.py
Labels: hacktoberfest-accepted

#25 Roman to Decimal Converter
  romantodecimal.py
Labels: hacktoberfest-accepted

#29 Odd or Even Number
  evensum.py
  oddoreven.py
Labels: hacktoberfest-accepted

#31 Guessing Game
  guessing.py
Labels: hacktoberfest-accepted

#32 Added function to check if number is palindrome
  palindrome.py
Labels: bug, hacktoberfest-accepted

#33 Password Generator
  passwordgen.py
Labels: hacktoberfest-accepted

#35 Tic Tac Game
  madlibs.py
  tictac.py
Labels: hacktoberfest-accepted

#38 Contact Book
  contactbook.py
Labels: hacktoberfest-accepted

#39 Number Guessing Game
  guessnumb.py
Labels: hacktoberfest-accepted

#40 Binary Search Engine
  binaryengine.py
Labels: hacktoberfest-accepted

#42 Desktop Notifier App
  notifier.py
Labels: hacktoberfest-accepted

#44 Sodoku Solver
  sudoku.py
Labels: hacktoberfest-accepted

#45 Photo Manipulation
  manipulate.py
Labels: hacktoberfest-accepted

#46 Minesweeper
  minisweeper.py
Labels: hacktoberfest-accepted

#47 Tetris
  tetris.py
Labels: hacktoberfest-accepted

#48 swap two variables python
  swaptwovariables.py
Labels: hacktoberfest-accepted

#53 odd or even in c
  odd_or_even.c
Labels: hacktoberfest-accepted

#51 sum of odd number using python
  sum.py
Labels: hacktoberfest-accepted

#59 Area of a circle
  cal.py
  circle.py
Labels: hacktoberfest-accepted

#60 Super Enjoyable Snake Game
  game.py
Labels: hacktoberfest-accepted

#61 Password Generator Super Cool
  genpw.py
Labels: hacktoberfest-accepted

#54 Sum of odd numbers
  sumofodd.c
Labels: hacktoberfest-accepted

#62 Odd or Even Finder
  odoreven.py
Labels: hacktoberfest-accepted

#58 Hacktoberfest even or odd
  even-odd.cpp
Labels: hacktoberfest-accepted
